### ISSUE TITLE
第五章示例代码有误

### ISSUE THREAD

**Issue by lolhezihehe** [nice-angular/ng-book-2#1]
第5章中的验证提示片段有误，比如5.6.1 整合代码的
`<div *ngIf="!sku.valid" class="ui error message">SKU is invalid</div>`
*ngIf不是CSS隐藏显示，所以尽管 *ngIf=true，Semantic UI中`.ui.form .error.message{display : none;}` 会导致该条提示信息不会出现。

**Comment by asnowwolf** [comment]
多谢，我会在验证后添加勘误。

**Comment by asnowwolf** [comment]
已验证并添加勘误。多谢！
